#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# SPDX-License-Identifier: GPL-3.0-or-later
#
# @copyright Copyright (c) 2026 Rafael Mendes
# @license   GPLv3+ <https://www.gnu.org/licenses/gpl-3.0.html>
# @link      GitHub <https://github.com/mendescrafael>
#
# This file is part of Docker Template.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Processo de inicialização, responsável por executar tarefas de configuração
# antes da inicialização da aplicação.
# -----------------------------------------------------------------------------

# Interrompe o script em caso de erros.
set -e

# Função auxiliar para saídas de logs.
log() {
    printf '[%(%Y-%m-%d %H:%M:%S)T] %s\n' -1 "$*"
}

# Validação de variáveis de ambiente obrigatórias.
validate_envs() {
    log "Validando variáveis de ambiente obrigatórias..."

    for var in "$@"; do
        if [[ -z "${!var:-}" ]]; then
            log "[ ERROR ] Variável obrigatória não definida: '${var}'"
            exit 1
        fi

        log "[ OK ] Variável obrigatória definida: '${var}'"
    done

    log "[ OK ] Todas as variáveis obrigatórias foram definidas"
}

# Validação dos diretórios e arquivos obrigatórios.
validate_paths() {
    local type="$1"
    shift

    case "${type}" in
        dir)
            log "Validando diretórios obrigatórios..."

            for path in "$@"; do
                [[ -d "${path}" ]] || {
                    log "[ ERROR ] Diretório obrigatório não encontrado: '${path}'"
                    exit 1
                }
            done
            ;;
        file)
            log "Validando arquivos obrigatórios..."
            
            for path in "$@"; do
                [[ -f "${path}" ]] || {
                    log "[ ERROR ] Arquivo obrigatório não encontrado: '${path}'"
                    exit 1
                }
            done
            ;;
        *)
            log "[ ERROR ] Tipo de validação inválido: '${type}'"
            exit 1
            ;;
    esac

    log "[ OK ] Validação concluída com sucesso"
}

# Inicialização do processo principal.
start_main_process() {
    if [[ "$#" -eq 0 ]]; then
        log "[ ERROR ] Nenhum comando principal foi informado ao container"
        exit 1
    fi

    log "Iniciando processo principal (${APP_SERVICE})..."
    exec "$@"
}

# Função principal de inicialização.
main() {
    log "Inicializando ENTRYPOINT..."

    # Validação de variáveis de ambiente obrigatórias.
    validate_envs \
        "APP_DIR" \
        "APP_SERVICE" \
        "APP_RUNTIME_USER" \
        "APP_RUNTIME_GROUP" \
        "DB_HOST" \
        "DB_PORT" \
        "DB_USER" \
        "DB_PASS" \
        "DB_NAME"

    # Validação dos diretórios obrigatórios.
    validate_paths dir \
        "${APP_DIR}"
    
    start_main_process "$@"
}

main "$@"
